server:
  port: 8764

#数据库的连接配置

spring:
  datasource:
    url: jdbc:mysql://10.11.60.183:3307/hyzg
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true


#  rabbitmq:
#    host: 192.168.24.22
#    username: wlkg
#    password: 123456
#    virtual-host: /wlkg
#    template:
#      exchange: wlkg.item.exchange
#      retry:
#        enabled: true
#        initial-interval: 10000ms
#        max-interval: 300000ms
#        multiplier: 2
#    publisher-confirms: true
